# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensor/
Content-Type: application/json

{
  "name": "ESP33",
  "description": "Датчик в коридоре возле двери"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensor/2/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurement/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 24.0
}

###

# получение информации по датчику
GET {{baseUrl}}/sensor/2/
Content-Type: application/json
